### PR TITLE
fix: add sip uri port if missing

### PR DESCRIPTION
**Pull request by InnovativeUS**
Add default port if it is missing in an address.

This is needed to ensure the requests without a port are matched in the connection pool

### CODE REVIEW

**Comment by emiago** [comment]
Default port is handled by transport layer, so if you send request and port is missing transport layer will add it. 
This comes couple times already, but library has no usage of this method. It was mostly added as read property, but sip URI has limited knowledge of what transport will be used?

**Comment by InnovativeUS** [comment]
Unfortunately if the request has no route, the address of the contact is used. 

sipgo/dialog_server.go:144

	// Check Route Header
	// Should be handled by transport layer but here we are making this explicit
	if rr := req.Route(); rr != nil {
		req.SetDestination(rr.Address.HostPort())
	}

That was where we were experiencing the issue

**Comment by emiago** [comment]
Hi @InnovativeUS can you actually test your code, by removing that line. Normally Route headers are handled by default. 
Problem is, I can not get reason anymore why I made this explicit. Probably there was old issue

**Comment by emiago** [comment]
Hi @InnovativeUS . Not sure do I get your last response correctly. If anything needs to done here, go ahead open issue. 
I will check that line my self once more.

**Pull request closed without merging**
